sudo: false
language: php
php:
- 5.5
- hhvm

matrix:
  fast_finish: true

addons:
  postgresql: "9.3"

before_script:
- cp app/config/parameters.yml.dist app/config/parameters.yml
- composer self-update
- composer install --prefer-source
- chmod -R 777 app/cache app/logs web/uploads
- psql -c "create user logincidadao with password '';" -U postgres
- psql -c "create database logincidadao with owner logincidadao" -U postgres
- echo y | php app/console doctrine:schema:update --force
- echo y | php app/console lc:database:populate batch/

script: phpunit -c app 

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
