parameters:
#    lc_validation.example.class: LoginCidadao\ValidationBundle\Example

services:
#    lc_validation.example:
#        class: %lc_validation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
